db.url=jdbc:mysql://mysql-3f6c3d24-auctionapp.c.aivencloud.com:17222/defaultdb?sslmode=REQUIRED
db.user=avnadmin
db.pass=AVNS_adDeNn47SmgXa6TdSrz
#db.url=jdbc:mysql://localhost:3306/auction_db
#db.user=root
#db.pass=Kh00ngn0iduoc
