db.url=jdbc:mysql://mysql-0211-auctionapp.g.aivencloud.com:17222/defaultdb?sslmode=REQUIRED
db.user=avnadmin
db.pass=AVNS_kXYBpGxeUknmO16mC3E
#db.url=jdbc:mysql://localhost:3306/auction_db
#db.user=root
#db.pass=Kh00ngn0iduoc
