db.url=jdbc:mysql://auction-db-klbc.mysql.database.azure.com:3306/auction_db?serverTimezone=Asia/Ho_Chi_Minh
db.username=azureuser
db.password=Kh00ngn0iduoc
#db.url=jdbc:mysql://localhost:3306/auction_db
#db.user=root
#db.pass=Kh00ngn0iduoc
