handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

org.example.server.config.level=OFF

org.example.server.network.level=INFO
org.example.server.services.level=INFO
org.example.server.ServerMain.level=INFO