handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=OFF
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

org.example.server.config.level=OFF

org.example.server.network.level=OFF
org.example.server.services.level=OFF
org.example.server.ServerMain.level=OFF